### PR TITLE
Export to PDF

### LINKED ISSUE #2: Feature Request: Export to PDF
Thanks for the great package! I can get printing to PDF via Chrome to work, but it would be much more convenient to generate the PDF directly via pandoc. Given that most posters will (at least currently) be destined to get exported to PDF for printing, are you considering adding this feature?

### PR DESCRIPTION
**Pull request by bbucior**
Closes #2 

Adds an optional `export_pdf` flag (enabled by default) to automatically convert the pandoc output from HTML to PDF using Google Chrome or Chromium.  The RStudio previewer will automatically open the PDF instead of the HTML output, facilitating rapid iteration.  If Chrome cannot write the PDF for some reason (most commonly because the file is open in another viewer), the RMarkdown error log will forward stderr from Chrome.

@jvcasillas Would you be willing to test this feature?  You can install the development version of the package using `devtools::install_github("bbucior/drposter@export-pdf", force=TRUE, dep=FALSE)`

### CODE REVIEW

**Comment by jvcasillas** [comment]
I'm getting an error on the install. 

```
Error: HTTP error 422.
  No commit found for SHA: export-pdf

  Rate limit remaining: 58/60
  Rate limit reset at: 2019-03-10 17:57:21 UTC
```

**Comment by jvcasillas** [comment]
Fixed. The link is: `devtools::install_github("bbucior/drposter@pdf-export", force=TRUE, dep=FALSE)`

**Comment by jvcasillas** [comment]
Works like a charm! Great addition to a great package. Thank you!

**Comment by bbucior** [comment]
Sorry for the typo.  Thanks for your help!

**Pull request merged**
